name: Build & Publish CV PDF

# Trigger on changes to data, script, or Quarto config
on:
  push:
    paths:
      - '_data/**'
      - 'scripts/generate_cv_qmd.py'
      - '_quarto.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout with full history so that we can push back
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Set up Python & regenerate CV.qmd
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install PyYAML
        run: pip install pyyaml
      - name: Generate CV.qmd
        run: python scripts/generate_cv_qmd.py

      # 3) Install Quarto, R, R packages
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("typstcv", repos = "https://kazuyanagimoto.r-universe.dev")'
          Rscript -e 'install.packages("rmarkdown")'

      # 4) Commit and push the updated PDF back into assets/
      - name: Render CV.qmd
        uses: quarto-dev/quarto-actions/render@v2

      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update CV.pdf"
        
      - name: GitHub push
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          directory: assets
