name: Build & Publish CV PDF

# Trigger on changes to data, script, or Quarto config
on:
  push:
    paths:
      - '_data/**'
      - 'scripts/generate_cv_qmd.py'
      - '_quarto.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout with full history so that we can push back
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Set up Python & regenerate CV.qmd
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install PyYAML
        run: pip install pyyaml
      - name: Generate CV.qmd
        run: python scripts/generate_cv_qmd.py

      # 3) Install Quarto CLI and R
      - name: Install Quarto CLI
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
      - name: Install renv
        uses: r-lib/actions/setup-renv@v2

      # 4) Commit and push the updated PDF back into assets/
      - name: Render and publish updated CV.pdf
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
